### ISSUE TITLE
Hot Potato crash

### ISSUE THREAD

**Issue by Caaine** [dataviruset/sm-hosties#38] opened 2016-01-07 00:33 UTC
https://crash.limetech.org/bpby3wcebtym

Hot Potato crashing the Server :sandal:

**Comment by data-bomb** [comment] 2016-01-07 00:55
What are the steps to reproduce?  What game?  The closest line in Hosties would be 
https://github.com/dataviruset/sm-hosties/blob/master/addons/sourcemod/scripting/hosties/lastrequest.sp#L3983
Not sure why that would be causing a server crash.

**Comment by Caaine** [comment] 2016-01-07 02:34
oh sry

CSGO and Player as a LR and the take Hot Potato on the menu and crash :(

**Comment by data-bomb** [comment] 2016-01-08 13:46
The first error indicates you did not install your translation file correctly or you are missing translations.  Fix the translation file issue first.

As to the other errors, we are checking if both T and CT clients are in game the same game tick as GetClientAbsOrigin is being called, so you should not receive that error if your Hosties and SourceMod are correctly installed.

**Comment by awillinger** [comment] 2016-01-30 13:55
I too am getting crashes with Hot Potato, also the language phrase not found error, despite all translation files being installed correctly (and actually having the phrase).

https://crash.limetech.org/xothef36c66v

**Comment by dataviruset** [comment] 2016-01-30 14:14
Maybe there's something wrong with the encoding of the file. You should not get that error message if the phrase exists. How did you add the translation files to the addons/sourcemod/translations/ folders?

**Comment by awillinger** [comment] 2016-01-30 15:50
Using SFTP via WinSCP default transfer setting.

**Comment by data-bomb** [comment] 2016-06-17 17:30
Still unable to duplicate @awillinger @Caaine is this happening with the latest version?

**Comment by Caaine** [comment] 2016-06-17 19:19
Enable Hot Potato for Testing^^

**Comment by awillinger** [comment] 2016-06-18 11:15
I have since closed my JB server, so can't tell anymore, sorry.

**Comment by data-bomb** [comment] 2016-09-24 18:51
Unable to replicate. Closing this issue. @Caaine feel free to re-open if you have the sequence of steps to replicate.

**Closed by data-bomb** 2016-09-24 18:51 UTC
Labels: bug
