### ISSUE TITLE
LR Issue after SM Update. (No Scope Battle)

### ISSUE THREAD

**Issue by balonfx** [dataviruset/sm-hosties#40] opened 2016-03-08 06:29 UTC
Hello,

After the recent SM update which assists in preventing blacklists due to !ws / !knife, Last Request for No Scope Battle.

Error log:
L 03/08/2016 - 01:32:24: [SM] Native "SetEntProp" reported: Cannot set m_iItemDefinitionIndex with "FollowCSGOServerGuidelines" option enabled.
L 03/08/2016 - 01:32:24: [SM] Displaying call stack trace for plugin "jailbreak/sm_hosties.smx":
L 03/08/2016 - 01:32:24: [SM]   [0]  Line 5204, hosties/lastrequest.sp::Timer_Countdown()

**Comment by data-bomb** [comment] 2016-03-08 12:50
Duplicate of #39 which is already resolved.  Compile the Alternate-Weapon-Spawning branch NOT the master branch.

**Closed by data-bomb** 2016-03-08 12:50 UTC
